DROP DATABASE IF EXISTS staff_db;
CREATE DATABASE staff_db;

USE staff_db;

CREATE TABLE employee(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT;
);

CREATE TABLE role(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT;
);

CREATE TABLE department(
    ID INTEGER PRIMARY KEY AUTO_INCREMENT;
);